import config

SQLALCHEMY_DATABASE_URI = config.SQLALCHEMY_DATABASE_URI
SQLALCHEMY_TRACK_MODIFICATIONS = config.SQLALCHEMY_TRACK_MODIFICATIONS
SECRET_KEY = config.SECRET_KEY
UPLOAD_FOLDER = config.UPLOAD_FOLDER
APPLICATION_ROOT = config.SUBDIRECTORY
SESSION_COOKIE_PATH = config.SUBDIRECTORY
SESSION_COOKIE_NAME = 'econom'

PERMANENT_SESSION_LIFETIME = config.PERMANENT_SESSION_LIFETIME
