# Generated by Django 3.0.3 on 2020-02-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0002_auto_20200226_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='econom.Section')),
            ],
        ),
    ]
