# Generated by Django 3.0.3 on 2020-03-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0004_auto_20200229_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CostCategory',
        ),
    ]
