# Generated by Django 3.0.3 on 2020-03-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0005_auto_20200301_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='costcategory',
            name='unique_category',
        ),
        migrations.AddConstraint(
            model_name='costcategory',
            constraint=models.UniqueConstraint(fields=('section', 'title'), name='unique_cost_category'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='econom.Section'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(fields=('section', 'title'), name='unique_income_category'),
        ),
    ]
