# Generated by Django 3.0.3 on 2020-03-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0006_auto_20200301_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econom.IncomeCategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econom.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econom.CostCategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econom.Wallet')),
            ],
        ),
    ]
