# Generated by Django 3.0.3 on 2020-03-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0007_cost_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cost',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='econom.Section'),
        ),
        migrations.AddField(
            model_name='income',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='econom.Section'),
        ),
    ]
