# Generated by Django 3.0.3 on 2020-03-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0008_auto_20200304_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='econom.CostCategory'),
        ),
    ]
