# Generated by Django 3.0.3 on 2020-03-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econom', '0009_auto_20200306_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='econom.CostCategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='econom.IncomeCategory'),
        ),
    ]
