"""empty message

Revision ID: 7856469df42a
Revises: c15989a713f8
Create Date: 2021-04-24 19:05:29.025235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7856469df42a'
down_revision = 'c15989a713f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('time_event', sa.DATETIME(), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('time_event', sa.DATETIME(), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    op.drop_table('expense')
    op.drop_table('wallet')
    # ### end Alembic commands ###
